# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_manager', '0001_initial'),
        ('people_and_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagerTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FileObj',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Upload the file', upload_to='')),
                ('name', models.CharField(help_text='Enter a name for the file', max_length=60, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('cases', models.ManyToManyField(related_name='related_files', to='case_manager.Case')),
                ('person', models.ManyToManyField(related_name='file_rel_to_person', to='people_and_property.Person')),
                ('tags', models.ManyToManyField(related_name='tagged_files_set', to='file_manager.FileManagerTags')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True, null=True)),
                ('cases', models.ManyToManyField(related_name='related_note_set', to='case_manager.Case')),
                ('people', models.ManyToManyField(related_name='notes_rel_to_person', to='people_and_property.Person')),
                ('tags', models.ManyToManyField(related_name='tagged_note_set', to='file_manager.FileManagerTags')),
            ],
        ),
    ]
