# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('description', markupfield.fields.MarkupField(blank=True, rendered_field=True)),
                ('description_markup_type', models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default=None, max_length=30, null=True)),
                ('_description_rendered', models.TextField(editable=False)),
                ('editors', models.ManyToManyField(related_name='editable_notebooks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_notebooks', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='viewable_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='notes_user_can_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Who do you want to be able to view the note?', related_name='notes_user_can_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
