# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0002_auto_20160312_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='people',
        ),
        migrations.AddField(
            model_name='note',
            name='editors',
            field=models.ManyToManyField(related_name='notes_user_can_edit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='viewers',
            field=models.ManyToManyField(help_text='Who do you want to be able to view the note?', related_name='notes_user_can_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
