# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_auto_20160313_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.Notebook'),
        ),
    ]
