# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_note_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='related_note_set', to='case_manager.Case'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
    ]
