# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_and_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When was this case created in our system?', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='When was this case updated in our system?', null=True)),
                ('date_started', models.DateField(help_text='What date did this case commence?')),
                ('date_ended', models.DateField(blank=True, help_text='What date did the case close?', null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed except payment', 'Closed case, payment pending'), ('closed', 'paid and closed')], default='open', help_text='What is the current status of this case?', max_length=50)),
                ('description_of_case', models.TextField(help_text='What is the description of this case?', max_length=500, null=True)),
                ('hourly', models.NullBooleanField(help_text='Are you getting paid by the hour?')),
                ('attorney_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What is the attorney hourly rate? If not specified, default for case type will be used', max_digits=15, null=True)),
                ('assistant_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What is the assistant hourly rate on this case? If notspecified, default for case type will be used', max_digits=15, null=True)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0.0, help_text='What is the total billed for this case?', max_digits=20, null=True)),
                ('total_billings_received', models.DecimalField(decimal_places=2, default=0.0, help_text='What is the total billings you have received?', max_digits=20, null=True)),
                ('client', models.ManyToManyField(related_name='case_set', to='people_and_property.Person')),
                ('related_parties', models.ManyToManyField(blank=True, help_text='Who else is related to the case (e.g., beneficiaries)', related_name='related_parties_set', to='people_and_property.Person')),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('billing_type', models.CharField(choices=[('hourly', 'hourly'), ('flat rate', 'flat rate'), ('contingency', 'contingency'), ('hourly-capped', 'hourly, but capped')], help_text='What type of billing is used for this sort of case?', max_length=20)),
                ('default_attorney_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What is the default hourly attorney rate?', max_digits=10, null=True)),
                ('default_assistant_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='What is the default hourly assistant rate?', max_digits=10, null=True)),
                ('default_flat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='If flat rate, what is the total fee?', max_digits=15, null=True)),
                ('hourly_cap', models.DecimalField(blank=True, decimal_places=2, help_text='If billing hourly with a total cap, what is the cap?', max_digits=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_set', to='case_manager.CaseType'),
        ),
    ]
