# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='@work', max_length=30)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='context',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='context',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='context',
            name='projects',
            field=models.ManyToManyField(related_name='context_for_project', to='tasks.Project'),
        ),
        migrations.AddField(
            model_name='context',
            name='tasks',
            field=models.ManyToManyField(related_name='context_for_task', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='context',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_contexts', to=settings.AUTH_USER_MODEL),
        ),
    ]
