# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160121_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_project',
        ),
        migrations.AddField(
            model_name='project',
            name='subordinate_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='_project_subordinate_projects_+', to='tasks.Project'),
        ),
    ]
