# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160125_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subordinate_projects',
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], default='3', help_text='Level refers to how high level a project is, between 1 and 3. A Level 1 project would be something like "start a marketing business", while Level 3 would be something like design a poster.', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='under_projects',
            field=models.ManyToManyField(blank=True, related_name='_project_under_projects_+', to='tasks.Project'),
        ),
    ]
