# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160126_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_project',
        ),
        migrations.AddField(
            model_name='task',
            name='related_projects',
            field=models.ManyToManyField(blank=True, to='tasks.Project'),
        ),
    ]
