# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_auto_20160126_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(help_text='Who has permission to see this project?', to=settings.AUTH_USER_MODEL, verbose_name='Who can view this project?'),
        ),
        migrations.AddField(
            model_name='task',
            name='viewers',
            field=models.ManyToManyField(help_text='Who do you want to be able to observe this task?', related_name='tasks_user_can_view', to=settings.AUTH_USER_MODEL, verbose_name='Users who can view'),
        ),
    ]
