# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20160213_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='context',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.ManyToManyField(to='tasks.Context'),
        ),
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.ManyToManyField(to='tasks.Context'),
        ),
    ]
