# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20160213_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='context',
            field=models.ManyToManyField(related_name='projects_under_context', to='tasks.Context'),
        ),
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.ManyToManyField(related_name='tasks_under_context', to='tasks.Context'),
        ),
    ]
