# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20160223_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_big_steps_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='_purpose_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='_vision_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='big_steps_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='vision_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='_notes_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='notes_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='big_steps',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='vision',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
    ]
