# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20160226_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_tasks', to='tasks.Project'),
        ),
    ]
